### ISSUE TITLE
The URL linked from "Download the Deck" is not publicly accessible

### ISSUE THREAD

**Issue by gmacario** [SOLARMA/hackafake-dashboard#3]
As pointed out by @xrmx on Telegram, 2018-04-16 17:14:50 CEST

> l'URL del deck è rotto :)

**Comment by gmacario** [comment]
The URL linked from "Download the Deck" looks broken.

As a matter of fact, the URL <https://github.com/SOLARMA/rokers-droidcon-hack/blob/master/HackAfakeFINALVERSION_VERA-ilovepdf-compressed%20(2).pdf> is just not publicly accessible, since repository <https://github.com/SOLARMA/rokers-droidcon-hack> is private.

**NOTE**: We cannot make the repository public until we solve other blocking issues - see https://github.com/SOLARMA/rokers-droidcon-hack/issues

**Workaround**: Send the .pdf file to all those who notice it.
This has the additional advantage that we will know who is interested in reading the Elevator Pitch.

**Comment by gmacario** [comment]
See offending code:
https://github.com/SOLARMA/hackafake-dashboard/blob/master/src/app/dashboard/dashboard.component.html#L32

**Comment by ludusrusso** [comment]
solved

**Comment by gmacario** [comment]
I confirm it works, but I need to clean my browser cache first.
